// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLtbqQR536N9RZdoMPsOKq5tTPXJH-hBQ',
    appId: '1:134286341875:web:f9b857098484f3dd7be986',
    messagingSenderId: '134286341875',
    projectId: 'flutterauthen-4bdc2',
    authDomain: 'flutterauthen-4bdc2.firebaseapp.com',
    storageBucket: 'flutterauthen-4bdc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvcglI4AlLa8w8T8W6TJovRObSf9oatQQ',
    appId: '1:134286341875:android:3eb9c11a82e300777be986',
    messagingSenderId: '134286341875',
    projectId: 'flutterauthen-4bdc2',
    storageBucket: 'flutterauthen-4bdc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvVL79uihxpwpcvCtc_zlrgEBeNQxGGSw',
    appId: '1:134286341875:ios:31e69ab903d38b4c7be986',
    messagingSenderId: '134286341875',
    projectId: 'flutterauthen-4bdc2',
    storageBucket: 'flutterauthen-4bdc2.appspot.com',
    iosBundleId: 'com.example.flutterBeginner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvVL79uihxpwpcvCtc_zlrgEBeNQxGGSw',
    appId: '1:134286341875:ios:41bde3b662fb17667be986',
    messagingSenderId: '134286341875',
    projectId: 'flutterauthen-4bdc2',
    storageBucket: 'flutterauthen-4bdc2.appspot.com',
    iosBundleId: 'com.example.flutterBeginner.RunnerTests',
  );
}
